"""tokens

Revision ID: 28762abd8877
Revises: 1c5e0b7af0a9
Create Date: 2024-10-27 17:25:44.161860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28762abd8877"
down_revision: Union[str, None] = "1c5e0b7af0a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operators.id"], use_alter=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operator_id"),
        sa.UniqueConstraint("value"),
    )
    op.add_column("operators", sa.Column("token_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "operators", "tokens", ["token_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "operators", type_="foreignkey")
    op.drop_column("operators", "token_id")
    op.drop_table("tokens")
    # ### end Alembic commands ###
