"""edit_note

Revision ID: 2af9baffefbc
Revises: 326d97aae262
Create Date: 2024-12-16 22:34:44.437064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af9baffefbc'
down_revision: Union[str, None] = '326d97aae262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('edit_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'edit_note')
    # ### end Alembic commands ###
