"""updates

Revision ID: 7bdb3959db59
Revises: 28762abd8877
Create Date: 2024-11-04 16:55:43.868083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7bdb3959db59"
down_revision: Union[str, None] = "28762abd8877"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operators", sa.Column("is_online", sa.Boolean(), nullable=False))
    op.drop_column("operators", "is_active")
    op.drop_constraint("tokens_operator_id_key", "tokens", type_="unique")
    op.drop_column("tokens", "operator_id")
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tokens",
        sa.Column("operator_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("tokens_operator_id_key", "tokens", ["operator_id"])
    op.add_column(
        "operators",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("operators", "is_online")
    # ### end Alembic commands ###
